import ReactDOM from "react-dom/client";
import "@fontsource/cormorant-garamond/latin-400.css";
import "@fontsource/cormorant-garamond/latin-500.css";
import "@fontsource/cormorant-garamond/latin-400-italic.css";
import "@fontsource/dm-sans/latin-400.css";
import "@fontsource/dm-sans/latin-500.css";
import "@fontsource/libre-baskerville/latin-400.css";
import App from "./App";
import "./style.css";
ReactDOM.createRoot(document.getElementById("root")!).render(<App />);
